import { z } from 'zod';
import type {
  RawYahooAuctionDetail,
  RawYahooAuctionSearchItem,
  RawYahooAuctionSearchResult,
} from '../yahoo-auctions-api.js';

export const searchItemSchema = z.object({
  auction_id: z.string().describe('Yahoo! Auctions auction ID'),
  title: z.string().describe('Listing title'),
  url: z.string().describe('Listing URL'),
  image: z.string().describe('Thumbnail image URL'),
  current_price_jpy: z.number().describe('Current auction price in JPY'),
  buyout_price_jpy: z.number().nullable().describe('Buyout price in JPY when available'),
  start_price_jpy: z.number().nullable().describe('Start price in JPY when available'),
  bids: z.number().describe('Current bid count'),
  time_left: z.string().describe('Visible remaining time text'),
  end_time_unix: z.number().nullable().describe('Auction end time as Unix timestamp when available'),
  free_shipping: z.boolean().describe('Whether the listing card indicates free domestic shipping'),
  seller_id: z.string().describe('Yahoo! Auctions seller ID when present in search result markup'),
  category_id: z.string().describe('Yahoo! Auctions category ID'),
  is_flea_market: z.boolean().describe('Whether the listing is marked as flea market style'),
  is_shopping_item: z.boolean().describe('Whether the listing is marked as shopping/store item'),
});

export const searchResultSchema = z.object({
  query: z.string().describe('Search query used'),
  source_url: z.string().describe('Yahoo! Auctions search URL fetched'),
  min_current_price_jpy: z.number().nullable().describe('Lowest current price among returned items'),
  min_buyout_price_jpy: z.number().nullable().describe('Lowest buyout price among returned items'),
  items: z.array(searchItemSchema).describe('Search result items'),
});

export const detailSchema = z.object({
  auction_id: z.string().describe('Yahoo! Auctions auction ID'),
  title: z.string().describe('Listing title'),
  url: z.string().describe('Listing URL'),
  description: z.string().describe('Plain text item description'),
  description_html: z.string().describe('Original description HTML when available'),
  current_price_jpy: z.number().nullable().describe('Current auction price in JPY'),
  buyout_price_jpy: z.number().nullable().describe('Buyout price in JPY when available'),
  start_price_jpy: z.number().nullable().describe('Start price in JPY when available'),
  bids: z.number().nullable().describe('Current bid count'),
  watchers: z.number().nullable().describe('Watch list count when available'),
  quantity: z.number().nullable().describe('Available quantity'),
  condition: z.string().describe('Condition text'),
  status: z.string().describe('Auction status'),
  images: z.array(z.string()).describe('Product image URLs'),
  seller_id: z.string().describe('Seller ID'),
  seller_display_name: z.string().describe('Seller display name'),
  seller_rating: z.string().describe('Seller rating summary'),
  seller_good_rating: z.string().describe('Seller good rating percentage'),
  seller_location: z.string().describe('Seller prefecture/location text'),
  shipping_payer: z.string().describe('Who pays shipping; Yahoo internal value such as seller or winner'),
  shipping_methods: z.array(z.string()).describe('Shipping method names'),
  ship_schedule: z.string().describe('Shipping schedule text'),
  end_time: z.string().describe('Auction end time'),
  category_path: z.array(z.string()).describe('Category breadcrumb names'),
  raw_source_url: z.string().describe('Fetched source URL'),
});

export const mapSearchItem = (item: RawYahooAuctionSearchItem) => ({
  auction_id: item.auctionId,
  title: item.title,
  url: item.url,
  image: item.image,
  current_price_jpy: item.currentPriceJpy,
  buyout_price_jpy: item.buyoutPriceJpy,
  start_price_jpy: item.startPriceJpy,
  bids: item.bids,
  time_left: item.timeLeft,
  end_time_unix: item.endTimeUnix,
  free_shipping: item.freeShipping,
  seller_id: item.sellerId,
  category_id: item.categoryId,
  is_flea_market: item.isFleaMarket,
  is_shopping_item: item.isShoppingItem,
});

export const mapSearchResult = (result: RawYahooAuctionSearchResult) => ({
  query: result.query,
  source_url: result.sourceUrl,
  min_current_price_jpy: result.minCurrentPriceJpy,
  min_buyout_price_jpy: result.minBuyoutPriceJpy,
  items: result.items.map(mapSearchItem),
});

export const mapDetail = (detail: RawYahooAuctionDetail) => ({
  auction_id: detail.auctionId,
  title: detail.title,
  url: detail.url,
  description: detail.description,
  description_html: detail.descriptionHtml,
  current_price_jpy: detail.currentPriceJpy,
  buyout_price_jpy: detail.buyoutPriceJpy,
  start_price_jpy: detail.startPriceJpy,
  bids: detail.bids,
  watchers: detail.watchers,
  quantity: detail.quantity,
  condition: detail.condition,
  status: detail.status,
  images: detail.images,
  seller_id: detail.sellerId,
  seller_display_name: detail.sellerDisplayName,
  seller_rating: detail.sellerRating,
  seller_good_rating: detail.sellerGoodRating,
  seller_location: detail.sellerLocation,
  shipping_payer: detail.shippingPayer,
  shipping_methods: detail.shippingMethods,
  ship_schedule: detail.shipSchedule,
  end_time: detail.endTime,
  category_path: detail.categoryPath,
  raw_source_url: detail.rawSourceUrl,
});
