import { z } from 'zod';
import type { RawMercariDetail, RawMercariSearchItem, RawMercariSearchResult } from '../mercari-api.js';

export const searchItemSchema = z.object({
  item_id: z.string().describe('Mercari item ID'),
  title: z.string().describe('Listing title'),
  url: z.string().describe('Listing URL'),
  image: z.string().describe('Thumbnail image URL'),
  price_jpy: z.number().nullable().describe('Listing price in JPY'),
  status: z.string().describe('Mercari listing status'),
  item_type: z.string().describe('Mercari item type'),
  seller_id: z.string().describe('Seller ID'),
  brand_name: z.string().describe('Brand name when available'),
  condition_id: z.string().describe('Mercari condition ID'),
  category_id: z.string().describe('Mercari category ID'),
  shipping_payer_id: z.string().describe('Mercari shipping payer ID'),
  shipping_method_id: z.string().describe('Mercari shipping method ID'),
  created_unix: z.number().nullable().describe('Created time as Unix timestamp when available'),
  updated_unix: z.number().nullable().describe('Updated time as Unix timestamp when available'),
  is_auction: z.boolean().describe('Whether the listing is a Mercari auction item'),
  auction_highest_bid_jpy: z.number().nullable().describe('Auction highest bid in JPY when available'),
  auction_total_bids: z.number().nullable().describe('Auction bid count when available'),
  auction_bid_deadline: z.string().describe('Auction bid deadline when available'),
});

export const searchResultSchema = z.object({
  query: z.string().describe('Search query used'),
  source_url: z.string().describe('Mercari search URL'),
  total_results: z.number().nullable().describe('Mercari reported result count when available'),
  next_page_token: z.string().describe('Token for the next page when available'),
  min_price_jpy: z.number().nullable().describe('Lowest price among returned items'),
  items: z.array(searchItemSchema).describe('Search result items'),
});

export const detailSchema = z.object({
  item_id: z.string().describe('Mercari item ID'),
  title: z.string().describe('Listing title'),
  url: z.string().describe('Listing URL'),
  price_jpy: z.number().nullable().describe('Listing price in JPY'),
  status: z.string().describe('Mercari listing status'),
  description: z.string().describe('Plain text item description'),
  images: z.array(z.string()).describe('Product image URLs'),
  condition: z.string().describe('Condition text'),
  category_path: z.array(z.string()).describe('Category breadcrumb names'),
  seller_id: z.string().describe('Seller ID'),
  seller_name: z.string().describe('Seller display name'),
  seller_rating_good: z.number().nullable().describe('Good rating count'),
  seller_rating_normal: z.number().nullable().describe('Normal rating count'),
  seller_rating_bad: z.number().nullable().describe('Bad rating count'),
  seller_rating_total: z.number().nullable().describe('Total seller rating count'),
  seller_star_rating: z.number().nullable().describe('Seller star rating score'),
  seller_verified: z.boolean().describe('Whether seller has SMS verification according to Mercari response'),
  likes: z.number().nullable().describe('Like count'),
  comments: z.number().nullable().describe('Comment count'),
  shipping_payer: z.string().describe('Shipping payer text'),
  shipping_method: z.string().describe('Shipping method text'),
  shipping_from_area: z.string().describe('Shipping origin prefecture/area'),
  shipping_duration: z.string().describe('Shipping duration text'),
  anonymous_shipping: z.boolean().describe('Whether anonymous shipping is enabled'),
  created_unix: z.number().nullable().describe('Created time as Unix timestamp when available'),
  updated_unix: z.number().nullable().describe('Updated time as Unix timestamp when available'),
  raw_source_url: z.string().describe('Fetched source URL'),
});

export const mapSearchItem = (item: RawMercariSearchItem) => ({
  item_id: item.itemId,
  title: item.title,
  url: item.url,
  image: item.image,
  price_jpy: item.priceJpy,
  status: item.status,
  item_type: item.itemType,
  seller_id: item.sellerId,
  brand_name: item.brandName,
  condition_id: item.conditionId,
  category_id: item.categoryId,
  shipping_payer_id: item.shippingPayerId,
  shipping_method_id: item.shippingMethodId,
  created_unix: item.createdUnix,
  updated_unix: item.updatedUnix,
  is_auction: item.isAuction,
  auction_highest_bid_jpy: item.auctionHighestBidJpy,
  auction_total_bids: item.auctionTotalBids,
  auction_bid_deadline: item.auctionBidDeadline,
});

export const mapSearchResult = (result: RawMercariSearchResult) => ({
  query: result.query,
  source_url: result.sourceUrl,
  total_results: result.totalResults,
  next_page_token: result.nextPageToken,
  min_price_jpy: result.minPriceJpy,
  items: result.items.map(mapSearchItem),
});

export const mapDetail = (detail: RawMercariDetail) => ({
  item_id: detail.itemId,
  title: detail.title,
  url: detail.url,
  price_jpy: detail.priceJpy,
  status: detail.status,
  description: detail.description,
  images: detail.images,
  condition: detail.condition,
  category_path: detail.categoryPath,
  seller_id: detail.sellerId,
  seller_name: detail.sellerName,
  seller_rating_good: detail.sellerRatingGood,
  seller_rating_normal: detail.sellerRatingNormal,
  seller_rating_bad: detail.sellerRatingBad,
  seller_rating_total: detail.sellerRatingTotal,
  seller_star_rating: detail.sellerStarRating,
  seller_verified: detail.sellerVerified,
  likes: detail.likes,
  comments: detail.comments,
  shipping_payer: detail.shippingPayer,
  shipping_method: detail.shippingMethod,
  shipping_from_area: detail.shippingFromArea,
  shipping_duration: detail.shippingDuration,
  anonymous_shipping: detail.anonymousShipping,
  created_unix: detail.createdUnix,
  updated_unix: detail.updatedUnix,
  raw_source_url: detail.rawSourceUrl,
});
